[숫자야구] 권순찬 미션 제출합니다.
econo-spring-2021/java-racingcar pull request #1
Opened 2021-05-13 03:38 UTC by Kwon770

요구 사항을 모두 충족하였지만, 질문이 있습니다.
1. 작성한 테스트 코드가 통과는 하지만 다음과 같은 경고가 뜹니다. 구글링해도 별다른 자료가 없는 같은데, 이에대해 아시는 정보가 있을까요?
![스크린샷 2021-05-13 11 26 20](https://user-images.githubusercontent.com/49567744/118073865-bb87f980-b3e7-11eb-9818-9e1aa85a3acd.png)

2. 입출력을 제외한 로직 함수에 대해서는 테스트 코드를 작성하였습니다. 다만, 함수 내의 지역변수를 이용한 메소드의 경우에는 테스트코드를 작성하기 어려운데 다른 방법이 있을까요? (e.g. ```Car.java``` 의 ```public void raceOnce()``` 의 경우, 메소드 내에서 생성한 난수를 통해 전진할지 말지를 정합니다. 이를 테스트코드 작성하는 방법이 있을까요? 지역변수를 접근하는 방법은 junit 구글링해도 안보이네요.)

2021-05-13 12:58 UTC, hotheadfactory requested changes
안녕하세요 순찬님 :)
전체적으로 잘 구현해 주셨어요! 피드백을 참고해서 고쳐 봅시다!!

2021-05-13 12:58 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Game.java
> +            winner[i] = car[i].getNameIfPositionSameOrEmpty(maxPosition);
승리한 Car 객체들이 아닌 승리한 자동차의 이름만을 모으고 있는데, 이러면 메소드 이름이 getWinnerNames()가 되거나 Car[]를 반환하도록 로직을 바꿔야 할 것 같아요!

2021-05-13 12:58 UTC, hotheadfactory commented on src/main/java/racingcar/view/GameIO.java
> +    public void printRaceResult(Car[] car) {
웬만하면 View단에는 도메인인 `Car`를 직접 전달하지 않고, 출력하는 데 필요한 정보만 String, List, Map 등으로 전달받는 것이 좋습니다.
예를 들면 이 경우에는 `Car[]` 대신 `HashMap<String, Integer>` 형태로 받아올 수 있겠죠.

**MVC 패턴에서는 View가 Model에 대한 정보를 알아서는 안 됩니다.**

2021-05-13 12:58 UTC, hotheadfactory commented on src/main/java/racingcar/view/GameIO.java
> +    public String[] inputCarNameArr(Scanner scanner) {
Scanner를 컨트롤러가 아닌 GameIO의 멤버 변수로 두는 것이 더 깔끔하지 않을까요?

2021-05-13 12:58 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +    public int getPositionIfBiggerOrComp(int comp) {
이 메소드의 구현을 보면 자기 자신의 position이 비교 대상보다 크면 그 position을 리턴하고, 아니면 비교 대상을 리턴하는, 즉 둘 중 큰 값을 리턴하는 것인데 `Math.max(this.position, comp)`를 이용하면 좀더 읽기 쉬운 코드가 될 것 같고, 메소드 이름도 좀 더 직관적인 이름으로 바꿔볼 수 있을 것 같습니다.

2021-05-13 12:58 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +        int moveChance = (int) (Math.random() * 10);
이 부분이 항상 랜덤 값이기 때문에 테스트가 어렵다고 하셨는데, 해결하기 위해선 난수 생성 부분을 별도의 클래스로 분리하고 따로 주입받아 사용하는 것을 생각해 볼 수 있어요.
(애초에 이 메소드, 난수 생성과 전진 가능여부 판정이라는 두 가지 일을 동시에 하고 있어요!)

그렇게 하면 난수 대신 특정 값을 집어넣어 차가 가는지 서는지 테스트할 수 있는 두 가지 방법이 생깁니다.
첫번째로 Mocking을 이용하여 난수 생성기 클래스를 흉내낸 가짜 클래스를 집어넣어 무조건 특정 숫자를 반환하도록 하는 방법이 있지만, 이 방법은 지금 사용하기에는 매우 어렵고 복잡합니다.
두 번째 방법은 '전략 패턴'입니다. 난수 생성기의 이름이 `RandomNumberGenerator`라고 가정했을 때, 이것이 `NumberGenerator`라는 인터페이스를 구현하게 하고 `raceOnce()`를 `NumberGenerator`에 의존하게 하면, 테스트 시에는 `RandomNumberGenerator` 대신 테스트 전용 `TestNumberGenerator`를 만들어 집어넣어 난수가 아닌 정해진 숫자를 사용하게 바꿀 수 있습니다.

2021-05-13 12:58 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Game.java
> +    public void setCar(Car[] _car) {
Getter와 Setter를 입/출력과 관련된 부분 외에서 사용하지 않을 수 있는 방법을 연구해 봅시다!
물론 Getter와 Setter를 통하는 것이 멤버 변수를 Public으로 열어두는 것보다는 안전하지만, 멤버 변수로 가지고 있는 것이 원시값이 아닌 '객체'인 경우 Getter로 밖으로 가지고 나온 상태에서 수정을 가하면 해당 객체는 메모리 상에서 하드 카피된 것이 아닌 원본과 같은 메모리 주소를 가리키므로 원본 객체까지 수정되어 버립니다. 불변성이 깨지는 것이죠. 
참고: https://m.blog.naver.com/PostView.nhn?blogId=writer0713&logNo=220984860512&proxyReferer=https:%2F%2Fwww.google.com%2F

2021-05-13 14:14 UTC, hotheadfactory commented
아, PR 명의 [숫자야구]로 되어 있는 부분이랑, 머지할 타깃 브랜치 명이 main으로 되어 있는 부분 수정 부탁드립니다.
현재 PR을 닫지 않고도 수정할 수 있어요!

2021-05-13 17:14 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +            game.setTryCount(Integer.parseInt(inputTryCount));
Setter는 가급적 사용을 피하는 게 좋습니다.
게임에 대한 모든 정보를 입력받은 다음에 Game의 생성자에 넣어 새 Game 객체를 생성하는 건 어떨까요?

2021-05-13 17:14 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Game.java
> +    private Car[] car;
배열보다 Collection을 사용하는 것이 좋습니다.
Car의 집합을 car로 이름붙이기보단 복수형인 cars를 이용하는 게 좋고요.
`List<Car> cars`로 바꿔보는 게 어떨까요?

2021-05-13 17:14 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Game.java
> +    private String[] carName;
'자동차의 이름' 이라는 정보는 '자동차들'이라는 필드 변수를 통해 얻을 수 있는 정보입니다.
굳이 중복해서 둘 필요가 없지요.

2021-05-13 17:14 UTC, hotheadfactory commented on src/main/java/racingcar/view/GameIO.java
> +        if (name.length() > 5) throw new TooLongNameException();
5라는 숫자가 하드 코딩되어 있습니다. 상수로 빼는 게 어떨까요?

2021-05-14 07:31 UTC, Kwon770 commented
피드백을 전부 수용하여 수정하였습니다. 단, HashMap 과 객체에 대한 불변성에 대한 추가 질문이 생겨서 스터디 시간때 질문하겠습니다!

2021-05-14 07:44 UTC, hotheadfactory requested changes
이전보다 코드가 한결 깔끔해졌네요!
아래 내용에 대해 다시 한 번 생각해 보고 적용해 봅시다. 이후 머지해 드리겠습니다.

2021-05-14 07:44 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +            io.catchNameException(carNames);
도메인의 인스턴스 변수의 제약 사항을 검사하고 예외를 throw하는 일은 뷰가 아닌 도메인이 해야 하지 않을까요?

2021-05-14 07:44 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +            io.catchTryCountException(tryCount);
이곳도 마찬가지로 뷰가 아닌 도메인에 책임을 지워 보아요!

2021-05-14 07:44 UTC, hotheadfactory commented on src/test/java/CarTest.java
> +        TestNumberGenerator testNumberGenerator = new TestNumberGenerator();
전반적으로 테스트가 빈약합니다. 모든 도메인 객체의 getter, setter를 제외한 모든 메소드에 대해 테스트해 보도록 합시다!
예외 테스트도 잊지 말고요.

2021-05-18 04:48 UTC, Kwon770 commented
예외 캐치 책임을 도메인으로 옮겼습니다. 아직 MVC 간의 역활 차이가 분명하지 않네요..
테스트에 관해서는 시도하였으나, 여러 문제가 발생하여 보류하였습니다. 테스트를 하는 과정에서 다음과 같은 오류가 발생합니다.

1.예외 사항을 위한 Junit의 ```@Test(expected = Exception.class)``` 에서 expected 가 cannot resolve symbol 로 해석됩니다. 그 대안으로 사용한 ```assertThrow()``` 또한 마찬가지입니다.
2. private 인 메소드와 필드에 접근하기 위해 다음 링크를 참고하였습니다. ( https://www.crocus.co.kr/1665 )
하지만, ```getDeclaredMethod()```, ```getDeclaredField()``` 부분에서 Unhandled exception: java.lang.NoSuchFieldException 이라는 예외가 발생합니다.

어떻게 해결할 수 있을까요..

2021-05-18 15:31 UTC, hotheadfactory approved these changes
1. assertThatThrownBy()를 이용해 봅시다!
2. private인 메소드를 굳이 직접 테스트할 필요는 없습니다. 결국엔 private이라고 할지라도 public인 다른 메소드의 부품으로 작동하기 때문에, 그 public 메소드를 테스트하여 잘 작동한다면 private 메소드도 Cover 된다고 볼 수 있습니다. (실제로 Run with Coverage 하면 Cover 된 것으로 나옵니다)

수고하셨습니다! Approve!

2021-05-30 05:06 UTC, merged