[자동차경주게임] 김송아 미션 제출합니다.
econo-spring-2021/java-racingcar pull request #2
Opened 2021-05-13 14:13 UTC by asong57

이번 미션을 하면서 헷갈렸던 부분이 있었는데
1. controller와 domain과 view의 경계
- view에서는 정말 입력과 출력의 결과만 보여줘야 하는지 아니면 입출력과 관련된 로직 또한 view에서 진행해야 하는지
- controller와 domain 에서 진행해야 하는 로직들의 경계 파악이 아직은 어려운 것 같습니다.

2. 테스트코드 작성
여러 로직들이 섞여있는 부분은 어떤 식으로 테스트 코드를 작성해야 할지 감이 안 오는 부분이 있습니다.

2021-05-13 18:06 UTC, hotheadfactory requested changes
안녕하세요 송아님:)
잘 구현해 주셨어요! 다만 설계에 대해 같이 고민해봐야 할 부분이 있는 것 같아요.
피드백에 대해 생각해 보시고 개선 후 다시 리뷰요청 주세요!

질문에 대한 답변입니다.
1. 입출력과 관련된 로직은 뷰에서 처리해야 합니다. 
이를테면 이번 자동차 경주 게임 미션 같은 경우 컨트롤러는 뷰에게 자동차의 이름-주행한 거리(숫자), 우승자 목록만을 전달하고, 이를 시각적으로 표시하는 기능은 전적으로 뷰의 몫입니다. 
사용자로부터 입력을 받는 것도 전부 뷰의 몫입니다. 예를 들어 사용자 이름을 String 형태로 전달받아 쉼표를 기준으로 쪼개서 List<String>으로 만드는 것도 뷰의 몫이라고 할 수 있습니다. 
단 뷰가 Car 객체를 생성해서 List<Car>를 리턴한다던지, List<Car>를 받아서 이름/주행거리/우승자를 검색해서는 안 됩니다. 뷰에 도메인 클래스가 import되는 일 자체가 없어야 합니다.
뷰에 경기 진행상황이나 결과 정보를 전달하는 방법은 지금처럼 String[]으로 쪼개서 보내도 되고, Map을 사용할 수도 있고, DTO를 사용할 수도 있습니다. (앞으로는 DTO를 사용할 일이 많아질거에요)

2. 여러 로직들이 섞여 있으면 당연히 테스트 코드 작성이 힘듭니다. 한 개의 메소드가 한 가지의 일만 하도록 정리한 다음에 테스트 코드를 작성해 봅시다!

2021-05-13 18:06 UTC, hotheadfactory commented on src/main/java/racingcar/controller/Game.java
> +    public static void main(String[] args) throws IOException {
main 메소드는 Application 클래스에 위치해야 합니다. Application에서 Game 객체를 만들어 게임을 시작할 수 있도록 리팩토링해 보아요!

2021-05-13 18:06 UTC, hotheadfactory commented on src/main/java/racingcar/controller/Game.java
> +    public static String[] carNameInput() throws IOException {
콘솔로부터 글자를 입력받는 기능은 View에 위치해야 합니다.

2021-05-13 18:06 UTC, hotheadfactory commented on src/main/java/racingcar/controller/Game.java
> +    private static String[] carNames;
carNames는 cars로부터 얻어낼 수 있는 정보이기 때문에 중복해서 필드 변수를 만들 필요가 없습니다.
프로그래밍상의 실수로 cars와 carNames의 갯수가 안 맞거나 이름이 뒤바뀔 위험성도 있습니다.

2021-05-13 18:06 UTC, hotheadfactory commented on src/test/java/GameTest.java
> +        String[] carNames = {"11111, 2, 3"};
String[]에 원소가 하나 있고, 그 내용이 "11111, 2, 3" 인 건가요?
입력받을 땐 하나의 String으로 입력받고, 쉼표를 기준으로 자동으로 나눠서 String[]에 저장해야 하지 않나요?

2021-05-13 18:06 UTC, hotheadfactory commented on src/test/java/GameTest.java
> +        assertThat("-").isEqualTo(Game.racingCarMove(true, racingCar).toString());
toString() 메소드를 이와 같이 UI 요소를 표시하는 용도로 사용하게 되면 나중에 요구 사항이 바뀌었을 때 뷰를 수정하기 위해 도메인을 손대야 하는 일이 생겨납니다.
UI 출력을 위해서는 getter를 사용해도 좋으니 뷰 로직이 자동차의 위치를 int로 받아 알아서 출력하도록 바꾸어 봅시다.

2021-05-13 18:06 UTC, hotheadfactory commented on src/main/java/racingcar/controller/Game.java
> +    public static StringBuilder[] racingCarsInit(StringBuilder[] racingCars) {
출력할 String을 만드는 모든 로직은 View에 위치하여야합니다.
간단히 말해서, 컨트롤러는 자동차의 이름, 위치, 우승자 등의 정보만 뷰에 전달하고 그 정보를 기반으로 UI를 꾸미는 일은 전적으로 뷰의 책임이어야합니다.

2021-05-15 08:45 UTC, asong57 commented
피드백 반영하여 코드 수정해보았습니다!
다시 피드백 주시면 감사하겠습니다 :)
바쁘실텐데 늘 섬세한 피드백 주셔서 감사해요!!!

2021-05-18 15:24 UTC, hotheadfactory approved these changes
수고하셨습니다 :)
추가 피드백 드린 부분은 따로 반영해 보시거나 다음 미션에 녹여내 보아요!
이만 Approve 하겠습니다.

2021-05-18 15:24 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +        return (int) ((Math.random() * 10000) % 10);
이 부분은 Car 객체의 상태와 아무런 연관이 없는 독립된 로직으로, Controller가 가지고 있어도 무방할 것 같습니다!

2021-05-18 15:24 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +    public int getPosition() {
현재 컨트롤러 로직 구현에 있어 getPosition()을 사용하고 있는데요, 
현재 코드상으로는 별 문제는 없지만 경우에 따라 getter를 씀으로서 인스턴스 변수의 값이 원치 않게 변조될 수 있습니다.

값을 직접 가져와서 컨트롤러에서 사용하는 getter 대신에 Car 객체에게 가지고 있는 값을 기반으로 판단을 내리길 요구하는 방향으로 (Tell, Don't Ask) 리팩토링할 수 있는지 생각해 봅시다!

* 비즈니스 로직을 거치지 않고 바로 뷰로 전달되는 경우에는 getter를 써도 문제가 없습니다

2021-05-18 15:24 UTC, hotheadfactory commented on src/main/java/racingcar/view/InputView.java
> +        System.out.println("경주할 자동차 이름을 입력하세요.(이름은 쉼표(,) 기준으로 구분)");
이런 안내문 String도 상수화시키면 후에 수정하거나 다국어화시키기에 편합니다.

2021-05-18 15:24 UTC, hotheadfactory commented on src/test/java/GameTest.java
> +public class GameTest {
Car에 대한 테스트가 없습니다. 작성해 주세요!
힌트: 어떠한 기능에 대해 테스트를 할 때는 메소드 단위로, 그 기능을 담당하는 메소드가 있는 클래스에 대해 테스트해야 합니다.

2021-05-30 05:06 UTC, merged