[Racing Car] 홍동건 미션 제출합니다.
econo-spring-2021/java-racingcar pull request #3
Opened 2021-05-13 15:13 UTC by Hongdonggeon

2021-05-13 19:01 UTC, hotheadfactory requested changes
안녕하세요 동건님:)
깔끔하게 잘 구현해 주셨어요! 아래 수정 사항만 반영해 주시면 더 멋진 코드가 될 것 같습니다. 

질문사항에 대한 답변입니다.
1. MVC 구조에 어긋나는 행위입니다. 모델에 변경 사항이 생기면 뷰도 고쳐야 하는 구조가 되면 안 됩니다.
2. 아무 것도 반환하지 않는 메소드는 대개 테스트하지 않습니다. 단 문제가 있을 시 예외를 throw하는 메소드라면 `assertThatThrownBy`를 통해 유효하지 않은 값을 넣었을 때 예외를 잘 던지는지 테스트하기도 합니다. 매개 변수가 없는 메소드는 대개 객체의 인스턴스 변수에 따라 반환값이 결정되는 경우가 많기 때문에 테스트 메소드 내에서 새 객체를 생성하고 생성자나 다른 메소드를 통해 조작해 테스트하고 싶은 환경을 만든 다음  반환값을 검사합니다.
3. 전역 변수는 C에서 사용되는 개념이고 클래스/인스턴스 변수나 상수를 두고 하신 말씀 같은데, 유틸리티 클래스화 할 수 있는 InputView, OutputView를 제외하면 딱히 잘못 쓰인 클래스/인스턴스 변수나 상수는 없어 보입니다. 지금처럼 잘 사용하시면 됩니다!

+ 커밋하실 때 기능 단위 커밋, 커밋 메시지 컨벤션 잊지 마세요!

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    private static final String NAME_SEPARATOR = ",";
상수 분리 👍

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    InputView inputView = new InputView();
InputView와 OutputView는 인스턴스 변수가 없고 매개변수에만 의존하기 때문에 객체를 만들지 않고 모든 메소드를 Static으로 바꾸어도 무방합니다. 이렇게 모든 메소드가 static이고 객체를 만들어 쓰지 않는 클래스를 유틸리티 클래스라고 합니다. 유틸리티 클래스에서 비즈니스 로직을 다루는 것은 좋지 않지만, 뷰는 흔히 유틸리티 클래스에서 다루곤 합니다.

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    private ArrayList<Car> arCar = new ArrayList<>();
arCar라는 변수명은 ArrayCar의 줄임말이겠지요?
변수명을 축약하는 것, 변수명에 자료형 이름이 포함되는 것 모두 피해야 합니다.
보통 배열이나 리스트의 이름은 ~s를 붙여 복수형으로 만듭니다. (예: cars)

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    public String[] separateName(String names) {
이 부분은 뷰에서 처리해야 합니다. 컨트롤러는 처리 완료된 이름 목록을 받아서 Car들을 생성하는 일만 해야 하고요.
쉽게 생각해서 어느 날 갑자기 콘솔에서만 돌아가던 자동차 경주 게임을 웹에서도 돌아가게 만들어야 한다고 생각해 봅시다.
컨트롤러는 차 이름을 받을 때 쉼표 떼고 다 처리된 데이터를 받고, UI에 의존적이지 않은 '차량별 이름과 위치, 최종 우승자' 만을 정리해서 보내야 컨트롤러/도메인에 대한 수정 없이 여러 가지 뷰를 동시에 지원할 수 있을 것입니다.

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    public ArrayList<Boolean> checkNameLength(String[] carNames) {
Car의 이름 길이가 유효한지 검사하는 방법에는, 컨트롤러에서 담당하는 방법도 있지만 Car에게 시키는 방법도 있습니다.
Car가 이름 길이 검사를 하게 되면, 컨트롤러를 거치지 않아도 이름 길이가 유효하지 않은 Car가 생성될 일이 절대 없겠지요?

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    public void oneTimeplayGame() {
메소드 명도 이 코드를 처음 보는 사람이 직관적으로 이해가 가능하도록 다듬을 필요가 있습니다 :)
(메소드 명은 주로 동사 형태)

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +    public int getPosition() {
지금 Car가 하는 일이 너무 없어요. Car와 관련된 로직을 Car에 책임으로 맡겨 봅시다!
가급적 뷰를 제외한 비즈니스 로직에 getter/setter를 사용하지 말고, 대신 필요한 동작을 '시켜서' Car 객체가 스스로 인스턴스 변수를 변화시키도록 합시다. 이를 TDA(Tell, Don't Ask) 원칙이라 합니다.

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/view/InputView.java
> +    private static Scanner input = new Scanner(System.in);
Scanner는 이렇게 한번만 선언해 두면, InputView 전체에서 사용할 수 있지요 👍

2021-05-13 19:01 UTC, hotheadfactory commented on src/main/java/racingcar/view/OutputView.java
> +    public void showPlayingResult(Car c) {
뷰는 도메인에 의존하면 안 됩니다. 아예 도메인 클래스가 import 되는 일 자체가 없어야 합니다.
그럼 Car를 불러오지 않고 어떻게 출력을 하느냐? 라고 생각하실 수 있는데, 방법은 많습니다.
Map을 쓰셔도 되고, DTO를 사용하셔도 됩니다.

2021-05-13 19:01 UTC, hotheadfactory commented on src/test/java/GameControllerTest.java
> +    void separateName()  {
보통 특정 메소드에 대한 테스트인 경우 해당 메소드 명에 ~Test를 붙여 테스트 메소드 이름을 짓습니다.
그렇게 정해진 건 아니고요, 그냥 DisplayName을 사용하지 않고 `void 차_번호_갯수_테스트()` 같이 한글로 테스트 메소드 명을 짓기도 합니다. 알아보기 편한 이름으로 자유롭게 지어 봅시다!

2021-05-21 12:25 UTC, Hongdonggeon commented on src/main/java/racingcar/controller/GameController.java
> +    private ArrayList<Car> arCar = new ArrayList<>();
넵 수정했습니다!

2021-05-21 12:27 UTC, Hongdonggeon commented on src/main/java/racingcar/controller/GameController.java
> +    public void oneTimeplayGame() {
넵 수정했습니돠

2021-05-21 12:34 UTC, Hongdonggeon commented on src/main/java/racingcar/view/OutputView.java
> +    public void showPlayingResult(Car c) {
showPlayingResult(Car c) 에서 showPlayingResult(String name, int position) 형식으로 변경하였습니다. Controller에서 showPlayingReuslt 메소드를 사용할 때 Car car 라는 객체를 만들어 showplayingReulst(c.getName(), c.getPosition()) 방법으로 사용하였는데 이 방법이 혹시 DTO를 사용한 것인가요??

2021-05-21 12:34 UTC, Hongdonggeon commented on src/test/java/GameControllerTest.java
> +    void separateName()  {
넵 테스트 코드 이름 지을 때 여러가지 방법으로 짓는 연습해보겠습니다~~ 감사합니다!!

2021-05-21 12:37 UTC, Hongdonggeon commented on src/main/java/racingcar/controller/GameController.java
> +    InputView inputView = new InputView();
넵 수정했습니다!! 혹시 그러면 뷰는 유틸리티 클래스로 구현하는 것이 더 좋은 방법일까요??

2021-05-21 12:38 UTC, Hongdonggeon commented on src/main/java/racingcar/controller/GameController.java
> +    public String[] separateName(String names) {
넵 수정했습니다!! 위 설명을 보고 MVC 구조에 대해 더 이해한 것 같습니다. 감사합니다!

2021-05-21 12:41 UTC, Hongdonggeon commented on src/main/java/racingcar/controller/GameController.java
> +    public ArrayList<Boolean> checkNameLength(String[] carNames) {
이 부분은 더 고민해보고 refactoring 해보겠습니다~!!

2021-05-26 14:11 UTC, hotheadfactory requested changes

2021-05-26 14:11 UTC, hotheadfactory commented on src/test/java/GameControllerTest.java
> +        String[] namesSeparate = InputView.separateName(names);
사실 이 부분은 `InputView.separateName(names);` 이라는 호출 부분에서도 알 수 있듯 View가 담당하는 부분이기 때문에 일반적으로 InputViewTest를 만들어 거기에 두는 것이 좋습니다. 물론 View는 아예 테스트를 하지 않아도 무방합니다.

2021-05-26 14:11 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +            carNames = InputView.separateName(InputView.inputNames());
InputView.inputNames()가 InputView.separateName()을 사용하게 만들어 메소드 호출을 단순화하는 게 더 좋지 않을까요?

2021-07-01 11:11 UTC, Hongdonggeon commented on src/main/java/racingcar/controller/GameController.java
> +            carNames = InputView.separateName(InputView.inputNames());
아 이런 방법이 있었네요! 수정했습니다 !!

2021-07-05 17:17 UTC, hotheadfactory approved these changes
동건님 수고하셨습니다~
다음 미션에서는 테스트를 보다 깔끔히 짜 봅시다!

2021-07-05 17:17 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +        if (carName.length() > MAX_NAME_LENGTH) {
'자동차의 이름이 5자 이하여야 한다'는 규칙은 Car 객체 내에서 관리하는 것이 좋아 보여요.
이 컨트롤러 대신 다른 곳에서 Car를 생성한다면 6자 이상의 이름을 가진 Car가 나와 버릴 수도 있기 때문입니다.
이 부분에 대해서는 다음 미션에서 다룰게요.

2021-07-05 17:17 UTC, hotheadfactory commented on src/test/java/GameControllerTest.java
> +class GameControllerTest {
현재 게임 컨트롤러에 대한 테스트만 있고 각 도메인 테스트가 없네요.

2021-07-08 12:31 UTC, merged