[자동차 경주 게임] 김규란 미션 제출합니다.
econo-spring-2021/java-racingcar pull request #4
Opened 2021-05-13 18:53 UTC by gxxrxn

늦어서 죄송합니다...
역시 기능 모두 구현하고나서 테스트 작성하려니 어렵네요..ㅠㅠ

2021-05-13 19:40 UTC, hotheadfactory requested changes
안녕하세요 규란님 :)
깔끔한 코드 잘 보았어요...! 약간의 수정 사항만 제안해 볼게요!

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +public class Car implements Comparable<Car> {
Comparable 활용 👍

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Cars.java
> +    private List<Car> cars;
일급 컬렉션을 사용하셨군요! 👍

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Cars.java
> +    public Map<String, Integer> getCarPositions() {
Map을 사용하는 것도 경기 정보를 뷰에 전달하기 위한 효과적인 방법이지만, DTO에 도전해 보시는 건 어떨까요?

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream()
stream 사용 👍

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +        inputView = new InputView();
InputView와 OutputView는 인스턴스 변수가 없고 매개변수에만 의존하기 때문에 객체를 만들지 않고 모든 메소드를 Static으로 바꾸어도 무방합니다. 이렇게 모든 메소드가 static이고 객체를 만들어 쓰지 않는 클래스를 유틸리티 클래스라고 합니다. 유틸리티 클래스에서 비즈니스 로직을 다루는 것은 좋지 않지만, 뷰는 비즈니스 로직이 없으므로 흔히 유틸리티 클래스를 사용합니다.

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +    private List<String> checkValidation(String carNames) throws NameException {
Car의 이름 길이가 유효한지 검사하는 방법에는, 컨트롤러에서 담당하는 방법도 있지만 Car에게 시키는 방법도 있습니다.
Car가 이름 길이 검사를 하게 되면, 컨트롤러를 거치지 않아도 이름 길이가 유효하지 않은 Car가 생성될 일이 절대 없겠지요?

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/controller/GameController.java
> +        return _carNames;
변수명은 카멜 케이스를 따라야 합니다.

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +    public void move(int step) {
step이란 변수명은 모호할뿐더러, 마치 'n칸 움직여라' 라는 메소드로 착각할 여지도 있어 보여요.
Car의 생성자에서 RandomNumGenerator를 받아서 그냥 `move()`만 해도 알아서 움직이게 하면 어떨까요?
(메모리 낭비를 막고 공정한 경기를 위해서 모든 Car에는 동일한 RandomNumGenerator가 들어가야겠지요? '싱글턴 패턴'을 이용해봅시다!)

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/controller/RacingGame.java
> +        MAX_TRIAL = maxTrial;
MAX_TRIAL과 IS_PLAYING은 변수입니다. 대문자와 underscore를 이용한 작명법은 상수에 사용하며, 변수는 카멜 케이스를 이용해야합니다.

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Cars.java
> +    public Cars(List<Car> cars) {
2개의 생성자를 두었군요. 오직 테스트만을 위해, 테스트에서만 쓰일 생성자를 추가하는 것은 취향에 따라서 싫어하시는 분들도 많은데요, 뭐 이정도는 테스트 코드가 지저분해지는 걸 막을 수 있다면 괜찮지 않나 싶습니다 :)

2021-05-13 19:40 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +        if (step >= 4) position += 1;
숫자 4는 상수화시킬 필요가 있을 것 같습니다!

2021-07-01 17:40 UTC, gxxrxn commented
피드백 반영했습니다 회형님!
NumberGenerator와 RamdomNumGenerator 중 어떤 객체가 Car 생성자로 전달되어도 move()만 하면 움직이도록 구현하는 부분이 조금 힘들었습니다..😭
제 머리로는 상속하는 방법밖에 생각나지 않아서....😭
DTO는 다음 미션부터 적용해보겠습니닷..😂

2021-07-05 17:21 UTC, hotheadfactory commented
NumberGenerator라는 인터페이스를 만들어 두고, DedicatedNumberGenerator(현재의 NumberGenerator)와 RandomNumberGenerator(현재의 RandomNumGenerator)가 이를 구현하게 하는 방법이 있을 것 같습니다.

이렇게 하면 Car가 무엇에 의존하냐에 따라 move()를 호출할 때 사전 지정된 대로 무조건 움직이거나 움직이지 않을 수도, 랜덤하게 움직일 수도 있습니다.

2021-07-08 15:26 UTC, gxxrxn commented
상속은 생각했으면서 인터페이스를 생각 못하다닛...... 🤦‍♀️
피드백 반영했습니다 회형님!!ㅎㅎ
항상 감사드려요 정말!! 덕분에 많이 배우고 있어요!! 🥰

2021-07-09 22:43 UTC, jbj616 approved these changes
지적할께 없네요 잘하셨습니다👍👍 
@hotheadfactory 궁금한게 if(){} 같은 조건문에 대한 컨벤션은 따로 없나요?? get를 사용하는 것에 대해서도... Stream 사용을 권장하나요???

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/Util/RandomNumGenerator.java
> +        this.value = (int)(Math.random() * bound);
RandomNumGenerator와 중복된 로직이 있는것같습니다 중복된 로직이 있을 경우 변경이 이루어질 때 여러군데를 손봐야하는 어려움이 있을것같네요

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/controller/GameController.java
> +    public GameController() {
빈 생성자를 사용하거나 사용하지 않는다면 위로직은 지워도 무관할 것같습니다

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/controller/RacingGame.java
> +        if (carNames == null) throw new CarNameException(CarNameException.NO_CAR_NAMES);
carNames.isEmpty 자료구조의 라이브러리를 적극 활용하면 좋을것같아요 (자바를 안한지 오래 됬는데 isEmpty가 null도 체크해주는 지 기억이 안나네요)

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/controller/RacingGame.java
> +        if (trialTime >= maxTrial) status = false;
컨벤션을 if(){}를 사용하셨는 데 혹시 약속한 컨벤션일까요??

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/domain/Car.java
> +public class Car implements Comparable<Car> {
Comparable이랑 Comparator 차이를 짚고 넘어가셨으면 좋겠습니다 알고계시는 것같지만 만약 알고리즘을 자바로 사용하신다면 유용할것같습니다

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/domain/Car.java
> +    public int compareTo(Car o) {
네이밍 체크 부탁드립니다

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/view/InputView.java
> +        if (input.length() <= 0) return null;
null 보다는 빈 객체를 리턴하는 것 좋아보여요 이유는 null를 리턴하면 디버깅이 힘들어지며 예상치 못한 에러가 발생할 수 있습니다 자바에서는 null을 최대한 자제하셨으면 좋겠습니다

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/view/OutputView.java
> +            StringBuilder builder = new StringBuilder();
StringBuilder와 Buffer의 차이점도 한번 짚고 넘어가셨으면 좋겠습니다

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/controller/RacingGame.java
> +        if (trialTime >= maxTrial) status = false;
보통 짧은 로직이여도 줄넘김을 하는 게 관례로 여겨집니다(회사마다 다르지만) 이유는 코드 줄이는 것도 의미가 있지만 그보다 조건문이라는 것을 인식시키는 게 더 의미가 크기 때문입니다
'''
if () {

}

'''
불편하시더라도 이런식으로 사용하셨으면 좋겠습니다 물론 컨벤션이 한줄로 처리해도된다면 괜찮습니다 
코딩의 목적은 기능구현도 있지만 유지보수도 있다는점 한번 생각하면 좋을 것같습니다

2021-07-09 22:43 UTC, jbj616 commented on src/main/java/racingcar/domain/Cars.java
> +    public void moveRandomAll() {
메소드명과 로직이 다른것같아요

2021-08-22 07:07 UTC, hotheadfactory approved these changes
병재님의 피드백을 참고해서 다음 미션 진행해 주세요!

2021-09-02 12:01 UTC, merged