[자동차 경주 게임] 김성혁 미션 제출합니다.
econo-spring-2021/java-racingcar pull request #5
Opened 2021-05-27 02:23 UTC by sunghyuki

기능 단위 커밋 못한 점 죄송합니다 ㅜㅜ

2021-05-30 05:05 UTC, hotheadfactory requested changes
안녕하세요 성혁님:)
요구사항에 맞게 잘 구현해 주셨어요!
테스트 코드도 완성해 봅시다!

2021-05-30 05:05 UTC, hotheadfactory commented on src/main/java/racingcar/controller/Race.java
> +        System.out.println(Constants.RACING_RESULT_MESSAGE);
컨트롤러가 직접 System.out.println을 호출하는 대신 뷰에 맡겨봅시다.

2021-05-30 05:05 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +        if(random.nextInt(10) >= Constants.MOVE_FORWARD_CONDITION) {
자동차를 움직이는 방법이 고정되어 있는데, 이를 의존성 주입을 이용해 리팩토링할 수 있을까요?
이와 같은 구조면 테스트할 때도 어려움이 있을 것 같아 보입니다.

2021-05-30 05:05 UTC, hotheadfactory commented on src/main/java/racingcar/domain/CarFactory.java
> +public class CarFactory {
'자동차 공장'이라는 이름과 달리, 자동차를 생성하지 않고 외부로부터 추가하는 방식인데요, 다른 이름을 사용할 수 있지 않을까요?

2021-05-30 05:05 UTC, hotheadfactory commented on src/main/java/racingcar/controller/Winner.java
> +    public static void getWinner(List<Car> racingCarList) {
인스턴스 변수가 없는 유틸리티 클래스 형식의 클래스로 보이는데요,
뷰가 아닌 비즈니스 로직에 있어 유틸리티 클래스를 남용하는 것은 좋지 않습니다.
이 메소드를 누구의 책임으로 할 수 있을지 고민해 볼까요?

2021-07-03 01:11 UTC, sunghyuki commented on src/main/java/racingcar/controller/Race.java
> +        System.out.println(Constants.RACING_RESULT_MESSAGE);
리뷰 반영하겠습니다!

2021-07-03 01:31 UTC, sunghyuki commented on src/main/java/racingcar/domain/CarFactory.java
> +public class CarFactory {
이름의 의미를 좀 더 생각하고 사용해야 했었는데 레이싱에 출전하는 자동차들이라는 의미면 좀 더 전달이 잘 될 수 있을 것 같네요!! 그에 맞게 이름을 수정해보겠습니다 👍🏻

2021-07-03 01:31 UTC, sunghyuki commented on src/main/java/racingcar/controller/Winner.java
> +    public static void getWinner(List<Car> racingCarList) {
**유틸리티 클래스를 남용하는 것은 좋지 않습니다.** 📝📝책임에 대해서 더 고민해보겠습니다!

2021-07-05 01:24 UTC, sunghyuki commented on src/main/java/racingcar/domain/Car.java
> +        if(random.nextInt(10) >= Constants.MOVE_FORWARD_CONDITION) {
리뷰 반영하겠습니다!

2021-07-09 23:13 UTC, jbj616 approved these changes
잘하셨습니다👍

2021-07-09 23:13 UTC, jbj616 commented on src/main/java/racingcar/controller/Game.java
> +            race.race(participatingCar, trial);
객체 이름과 매소드 이름이 중복되었습니다

2021-07-09 23:13 UTC, jbj616 commented on src/main/java/racingcar/controller/Race.java
> +        if(random.nextInt(10) >= Constants.MOVE_FORWARD_CONDITION) {
return 조건; 으로 로직을 수정하시면 로직의 길이를 줄일 수 있을것같습니다

2021-07-09 23:13 UTC, jbj616 commented on src/main/java/racingcar/controller/Race.java
> +        winner = racingCarList.stream().filter(car -> (car.getPosition() == positionOfWinner)).collect(Collectors.toList());
stream 사용하실 때 .메소드(체이닝) 마다 줄넘김을 하시면 가독성이 좋아질것같습니다

2021-07-09 23:13 UTC, jbj616 commented on src/main/java/racingcar/view/InputView.java
> +    private String[] carName;
List와 배열의 차이점에 대해서 한번 생각해보셨으면 좋겠습니다 여기서 배열을 사용한 것이랑 List를 사용하셨을 때 어떠한 장단점이 있는지..

2021-07-09 23:13 UTC, jbj616 commented on src/main/java/racingcar/controller/Race.java
> +        if(judgeMovingCondition()) {
judge단어가 적절한지 모르겠네요 is can... 같은 조건에 대한 직관적인 단어가 필요해보입니다

2021-07-09 23:16 UTC, jbj616 approved these changes

2021-07-09 23:16 UTC, jbj616 commented on src/main/java/racingcar/controller/Game.java
> +    private Scanner scanner;
스캐너가 inputview에 있는게 더 어울릴것같은데 한번 생각해보셨으면 좋겠습니다

2021-07-09 23:16 UTC, jbj616 commented on src/main/java/racingcar/controller/Race.java
> +        if(random.nextInt(10) >= Constants.MOVE_FORWARD_CONDITION) {
현재 로직이 더 가독성이 좋습니다 무엇이 좋을지는 생각 해보셨으면 좋겠습니다

2021-07-09 23:16 UTC, jbj616 commented on src/main/java/racingcar/domain/ParticipatingCar.java
> +    public void addRacingCar(Car car) {
객체명과 중복되는 단어가 보입니다

2021-07-10 06:24 UTC, sunghyuki commented on src/main/java/racingcar/controller/Game.java
> +            race.race(participatingCar, trial);
메소드명 변경했습니다!

2021-07-10 06:25 UTC, sunghyuki commented on src/main/java/racingcar/controller/Race.java
> +        if(random.nextInt(10) >= Constants.MOVE_FORWARD_CONDITION) {
로직의 길이 vs. 가독성에 대해서 생각해보겠습니다 감사합니다 👍🏻

2021-07-10 06:34 UTC, sunghyuki commented on src/main/java/racingcar/controller/Race.java
> +        if(judgeMovingCondition()) {
좀 더 읽기 쉬운 코드가 되도록 메소드명 변경하겠습니다

2021-07-10 06:40 UTC, sunghyuki commented on src/main/java/racingcar/view/InputView.java
> +    private String[] carName;
배열은 메모리 공간이 연속적으로 할당되어 있고 정적이기 때문에 컴파일 이전에 크기를 지정해줘야 하지만, 리스트는 동적이기 때문에 크기가 변할 수 있고 불연속적인 메모리 공간을 가지고 있는 것이 특징입니다.  데이터의 크기가 정해져 있고 추가적인 삽입/삭제 행위가 일어나지 않기에 배열을 사용하는 게 좀 더 효율적이지 않을까요?

2021-07-10 06:46 UTC, sunghyuki commented on src/main/java/racingcar/controller/Game.java
> +    private Scanner scanner;
InputView에서 책임을 갖는 게 맞을 것 같네용 🙇🏻‍♂️

2021-07-10 06:53 UTC, sunghyuki commented on src/main/java/racingcar/domain/ParticipatingCar.java
> +    public void addRacingCar(Car car) {
파라미터의 네임을 객체명과 중복되게 사용하는 것은 어떤 문제가 있을까요?

2021-07-10 06:54 UTC, hotheadfactory commented on src/main/java/racingcar/view/InputView.java
> +    private String[] carName;
반면 List가 가지는 장점이라면 stream을 사용 가능하며, 배열에 잘못된 타입의 변수를 삽입할 경우(예를 들어 Long 배열에 String을 삽입하는 실수를 할 경우) 런타임에서야 오류를 알 수 있는 반면 리스트의 경우 제네릭의 특징에 따라 컴파일 타임에 감지 가능하다는 장점이 있어 배열이 꼭 필요한 것이 아니면 리스트를 사용하는 것이 더 선호됩니다(Effective Java 164페이지 참조).

2021-07-10 06:56 UTC, sunghyuki commented on src/main/java/racingcar/view/InputView.java
> +    private String[] carName;
오호 회형님 감사합니다 🙇🏻‍♂️ 컴파일 타임에 버그를 감지할 수 있는 제네릭의 특징을 생각했을 때 이점이 충분히 있다고 생각되네요!

2021-07-10 13:26 UTC, hotheadfactory commented on src/main/java/racingcar/domain/ParticipatingCar.java
> +    public void addRacingCar(Car car) {
자료형을 포함하는 메소드명을 짓는 것은 권장되지 않습니다. `participatingCar.addRacingCar` 와 같이 사용될때 동어반복이 될 뿐더러, 추후에 인스턴스 변수의 자료형을 바꿔야 할 때 메소드명도 같이 바꿔야 하는 등의 문제가 발생하기 때문입니다.

2021-07-11 09:19 UTC, hotheadfactory approved these changes
수고하셨습니다! Approve 드릴게요!

2021-07-17 15:03 UTC, merged