java-racingcar 미션 제출합니다.
econo-spring-2021/java-racingcar pull request #6
Opened 2021-08-19 03:42 UTC by mywnajsldkf

계속 반복해서 코드를 수정하다보니 진전이 없는 것 같아 우선 제출하겠습니다.

2021-08-20 14:51 UTC, hyukjin-lee commented
고생하셨습니다 ~ ~

2021-08-20 14:51 UTC, hyukjin-lee approved these changes
고생하셨습니다~~

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +public class Controller {
무슨 역할을 하는 Controller 인지 명시해주면 어떨까요~?

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +    // static List<Object> cars = new ArrayList<Object>();
PR 요청 전에 주석처리한 부분은 과감히 삭제하거나, 삭제가 불가능하다면 사유를 적어주는건 어떨까요?

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +    private static Car[] cars = new Car[10];
배열보다는 리스트를 활용해보는게 어떨까요?
(참고 : [effective java item 28](https://madplay.github.io/post/prefer-lists-to-arrays]))

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +    public static List<String> racingCars = getRacingCars();
Controller 도 하나의 객체로 간주하고, 이러한 상태 할당과 메서드 실행을 별도의 public(not static) 메서드에서 진행하는게 어떨까요?

행위(메서드)를 통해 상태의 변경을 캡슐화 하는 코드를 작성해보시면 좋을 것 같습니다.

그러다보면 굳이 클래스의 필드 변수로 가지고 있지 않아도 되고 메서드 레벨의 변수로만 사용이 되어도 되는 것들이 보일거에요.

지금은 모든 클래스에 main 함수를 적용해야한다는 생각을 가지고 계신 듯 합니다~

실제 java 의 main 함수는 프로그램의 진입점으로서 한 군데에만 존재합니다. 

지금 적용하신 main 함수는 main 이라는 이름을 가진 단순 static 함수일 뿐이구요.

아직 익숙하지 않으셔서 그렇지 조금만 반복하면 금방 객체지향 코드에 익숙해지실겁니다.

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +    public static void main() {
static 메서드는 언제 사용하고, main 메서드란 어떤 역할인지 학습해보시면 좋을 것 같습니다~

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +        // 자동차 할당
대부분의 변수나 메서드에 주석을 작성하셨는데 주석은 최대한 작성을 지양하는 것이 서비스 코드 특성상 이롭습니다.

주석이 유용한 경우는 history(why) 가 코드의 흐름에서 중요한 역할을 하는 경우, 메서드명과 코드 가독성으로는 이를 나타내기 힘들기 때문에 commit 이나 주석으로 남기는 것이 좋습니다.

그 외에는 코드 가독성으로 설명하기 위해 노력해야하고, 주석은 굳이 변경하지 않아도 서비스의 동작에 해를 끼치지 않기 때문에 시간이 흐를수록 방치되는 경우가 많습니다.

그로 인해 잘못된 주석으로 해석을 잘못하여 오히려 장애의 요소가 되는 경우가 종종 있습니다.

이를 염두에 두고 주석을 최대한 줄여보는 코드를 작성해보시면 어떨까요?

이 부분도 메서드명이 충분히 좋아서 그걸 해석한 정도인 주석은 필요하지 않을 것 같다는 의견입니다~

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/Application.java
>      public static void main(String[] args) {
main 메서드의 흐름이, 

view 를 통해 입력을 받고, 입력받은 결과를 반환해서 controller 의 어느 메서드에 전달한 후, 

controller 에서 Car 객체를 움직이게 시켜서(메서드를 통해) 그 결과를 반환받고, 

그걸 가지고 view 를 통해 systemout 으로 출력을 하는 식의 흐름으로 작성해보면 어떨까요?

2021-08-20 14:51 UTC, hyukjin-lee commented on src/main/java/racingcar/controller/Controller.java
> +    public static List<String> racingCars = getRacingCars();
이 리뷰가 먼저 반영되어야 그 다음 리뷰를 진행할 수 있을 것 같습니다 ~

혹시 여기서 궁금한 점이나, 이해안되거나, 추가적으로 참고할만한 자료들이 필요하시면 말씀해주세요 !

2021-08-25 23:08 UTC, mywnajsldkf commented on src/main/java/racingcar/controller/Controller.java
> +    private static Car[] cars = new Car[10];
자료 감사합니다!

2021-08-25 23:08 UTC, mywnajsldkf commented on src/main/java/racingcar/controller/Controller.java
> +    public static List<String> racingCars = getRacingCars();
오호!!! 감사합니다

2021-08-25 23:17 UTC, mywnajsldkf commented
@hyukjin-lee 
작성해주신 피드백 바탕으로 수정하여 commit하였습니다. 피드백과 자료 덕분에 코드작성에 있어 도움을 얻을 수 있었습니다.

코드를 작성하면서 궁금한 점이 있습니다. 코드가 깊숙하게 들어간다는 느낌인데요.
예를 들어 a method안에서 b method를 접근하고, b는 c를 접근하는 코드가 작성될 때 입니다.
그림으로 표현한다면 이런 그럼일 것 같네요.
```
a
 -- b
     -- c
```
구조가 복잡해진다는 느낌이 들었는데, 이런 계층을 허용하는 범위가 있다면 몇단계정도까지 허용할까요? 그리고 이런 코드를 피해야한다면 어떻게 피해야하는지 궁금합니다.

2021-08-28 16:36 UTC, hotheadfactory requested changes
안녕하세요, 정인님!
리뷰를 차근차근 반영해 봅시다...!!

2021-08-28 16:36 UTC, hotheadfactory commented on src/main/java/racingcar/controller/RacingController.java
> +        racingView.printBlankLine();
컨트롤러에서 뷰에 '우선 빈 줄을 하나 출력하고, 승자를 촐력해라' 란 명령을 내리는 것은 뷰의 책임 범위를 침범한 것 같은 느낌이 드네요.

**만약 뷰가 다른 것으로 바뀌어야 하는 상황이 생겨도 쉽게 변경할 수 있도록** 리팩토링해 보는 게 어떨까요?

2021-08-28 16:36 UTC, hotheadfactory commented on src/main/java/racingcar/controller/RacingController.java
> +        return movement;
지금 movement라는 int 변수를 리턴하는 방식으로 되어 있는데요, 레이싱 게임 요구 사항을 보면 무조건 한번에 1칸씩만 움직이기 때문에 움직임 여부를 판단하는 이 메소드의 리턴값은 boolean이 되는 것이 더 적합하지 않을까요?
또한 **메소드의 이름이 적합한지, 이 로직이 Controller의 책임이 되는 것이 맞는지** 도 고민해 보아요!

2021-08-28 16:36 UTC, hotheadfactory commented on src/main/java/racingcar/domain/Car.java
> +    public void setCarMovement(int number){
Setter는 가급적 사용하지 않는 게 좋습니다.

Car가 직접 자신의 position을 바꾸게 하는 게 어떨까요?

2021-09-06 15:46 UTC, mywnajsldkf commented
@hotheadfactory 
코멘트 확인 후 수정 완료하였습니다. 덕분에 불필요한 메소드, 파라미터가 줄었습니다. 감사합니다 :)

2021-09-12 16:27 UTC, hotheadfactory requested changes
리뷰 늦어서 죄송합니다. 몇 가지만 수정해 주시면 바로 Approve 드릴게요!

2021-09-12 16:27 UTC, hotheadfactory commented on src/test/java/racingcar/controller/RacingControllerTest.java
> +    //@DisplayName("경주 시작할 자동차 할당")
테스트가 모두 주석 처리되어 있는데요, 작동하지 않아서 주석 처리해두신 건가요?

2021-09-12 16:27 UTC, hotheadfactory commented on src/main/java/racingcar/controller/RacingController.java
> +            printView.printRacingBroadCast(name, d);
컨트롤러가 뷰에 의존적인 것 같아요.
'한 줄을 띄운 다음, 각각의 자동차 위치를 출력해라' 가 아닌 '모든 자동차 위치를 출력해라' 라는 명령을 뷰가 알아서 처리하도록 바꿔 보면 어떨까요?

2021-09-12 16:27 UTC, hotheadfactory commented on src/main/java/racingcar/controller/RacingController.java
> +    public void startRacing(){
다른 클래스에서 의존하지 않는, 컨트롤러 로직만을 위한 메소드는 private로 닫아 두도록 합시다.

2021-09-22 06:40 UTC, mywnajsldkf commented on src/main/java/racingcar/controller/RacingController.java
> +            printView.printRacingBroadCast(name, d);
@hotheadfactory 이 부분 계속 고민해봤는데 잘 이해가 가지 않아요ㅠㅠ 혹시 보충설명 부탁드려도 될까요?

2021-09-22 06:40 UTC, mywnajsldkf commented on src/test/java/racingcar/controller/RacingControllerTest.java
> +    //@DisplayName("경주 시작할 자동차 할당")
@hotheadfactory 앗! 이 테스트 작성하다가 제 코드가 테스트 코드를 작성하기 어려운 코드인 것 같아서 그만두고 리팩토링먼저 하였습니다~ 다시 작성해서 커밋하겠습니다

2021-09-22 16:16 UTC, mywnajsldkf commented on src/main/java/racingcar/controller/RacingController.java
> +            printView.printRacingBroadCast(name, d);
@hotheadfactory 
회형님 이 부분 수정해서 반영했습니다~ 

(_한 줄을 띄운 다음,_ -> 이 내용은 생략한다고 했을 때)

각각의 자동차 위치를 출력해라 vs 모든 자동차 위치를 출력해라 라는 명령에서 후자를 지향하는 부분이 잘 이해가 가지 않아 이 부분 질문드립니다!

2021-09-24 06:19 UTC, hotheadfactory commented on src/main/java/racingcar/controller/RacingController.java
> +            printView.printRacingBroadCast(name, d);
@mywnajsldkf 
간단하게 말하면, 각각의 자동차 위치를 출력할 때마다 컨트롤러가 뷰를 호출하고, 줄바꿈 명령도 내리는 것은 컨트롤러가 뷰의 레이아웃에 적극적으로 개입하는 것이 되겠지요?
컬렉션이나 맵, DTO 등을 이용해 모든 자동차의 위치를 한번에 전달하고 구체적인 출력은 뷰가 알아서 하는 것이 좋겠다는 의미였습니다~

2021-10-07 11:23 UTC, hotheadfactory approved these changes
수고하셨습니다. 다음 미션으로 넘어가 봅시다!!

2023-06-30 17:20 UTC, closed without merging